spring.application.name=OpenBook
openbook.google-books.api-key=${GOOGLE_BOOKS_API_KEY:}
server.port=${PORT:8080}

openbook.selenium-source.enabled=false
openbook.selenium-source.url=https://www.gutenberg.org/ebooks/search/?query={term}
openbook.selenium-source.name=Fonte Selenium
openbook.selenium-source.result-selector=a[href]
openbook.selenium-source.title-selector=
openbook.selenium-source.cover-selector=img
openbook.selenium-source.browser-binary=
openbook.selenium-source.driver-path=C:/msedgedriver.exe
